use_frameworks!

platform :ios, '9.0'

target 'SellServicesCore_Example' do
  pod 'SellServicesCore', :path => '../'

  target 'SellServicesCore_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
